version: '3'

services:
  nginx:
    image: crpi-vd2np7sloa8wv5h3.cn-qingdao.personal.cr.aliyuncs.com/rhzz/nginx:latest
    ports:
      - "8021:8021"
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../download:/download
    depends_on:
      python:
        condition: service_healthy
    restart: always

  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ../download:/download
    restart: always
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
